spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
    open-in-view: false
    hibernate:
      ddl-auto: none

  mssql:
    datasource:
      jdbc-url: jdbc:sqlserver://host.docker.internal:1433;databaseName=etimetracklite1;encrypt=false;trustServerCertificate=true
      username: sa
      password: admin@123
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 300000
        connection-timeout: 20000
        max-lifetime: 1200000
        connection-test-query: SELECT 1
        validation-timeout: 5000
        pool-name: mssql-connection-pool

  mysql:
    datasource:
      jdbc-url: jdbc:mysql://host.docker.internal:3306/leo
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 300000
        connection-timeout: 20000
        max-lifetime: 1200000
        connection-test-query: SELECT 1
        validation-timeout: 5000
        pool-name: mysql-connection-pool

logging:
  file:
    name: /app/logs/syncer.log
  level:
    root: INFO
    com.udyata.syncer: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

sync:
  interval:
    milliseconds: 300000
  batch:
    size: 50
    timeout: 30